"""empty message

Revision ID: a27606fea59a
Revises: 
Create Date: 2020-11-20 15:49:45.838522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27606fea59a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('date_joined', sa.DATETIME(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    keep_existing= True
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True),
    keep_existing= True
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    keep_existing= True
    )
    op.create_index('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq', 'auth_user_user_permissions', ['user_id', 'permission_id'], unique=1)
    op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    keep_existing= True
    )
    op.create_index('django_content_type_app_label_model_76bd3d3b_uniq', 'django_content_type', ['app_label', 'model'], unique=1)
    op.create_table('auth_user_groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    keep_existing= True
    )
    op.create_index('auth_user_groups_user_id_group_id_94350c0c_uniq', 'auth_user_groups', ['user_id', 'group_id'], unique=1)
    op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('left_company_id', sa.INTEGER(), nullable=False),
    sa.Column('right_company_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['left_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['right_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    keep_existing= True
    )
    op.create_index('matches_right_company_id_17e298fb', 'matches', ['right_company_id'], unique=False)
    op.create_index('matches_left_company_id_ae152d81', 'matches', ['left_company_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    keep_existing= True
    )
    op.create_index('auth_permission_content_type_id_codename_01ab375a_uniq', 'auth_permission', ['content_type_id', 'codename'], unique=1)
    op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action_time', sa.DATETIME(), nullable=False),
    sa.Column('object_id', sa.TEXT(), nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), nullable=False),
    sa.Column('change_message', sa.TEXT(), nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action_flag', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('"action_flag" >= 0)'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    keep_existing= True
    )
    op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('permission_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    keep_existing= True
    )
    op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq', 'auth_group_permissions', ['group_id', 'permission_id'], unique=1)
    op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('applied', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    keep_existing= True
    )
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', sa.TEXT(), nullable=False),
    sa.Column('expire_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    keep_existing= True
    )
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False, keep_existing= True)
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=512), nullable=False),
    sa.Column('website', sa.VARCHAR(length=512), nullable=True),
    sa.Column('email', sa.VARCHAR(length=512), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=512), nullable=True),
    sa.Column('address', sa.VARCHAR(length=512), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=512), nullable=True),
    sa.Column('city', sa.VARCHAR(length=512), nullable=True),
    sa.Column('country', sa.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    keep_existing= True
    )
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    keep_existing= True
    )
    # ### end Alembic commands ###
